ash-project/ash_phoenix

lib/ash_phoenix/form_data/error.ex
=> Add form errors for invalid arguments

CHANGELOG.md
=> Note regression in 0.4.19

test/form_test.exs
These are a riff on the existing tests checking that the correct field gets any errors. When validate is used before submit, the nested errors end up on the root form
=> test: Add failing tests

test/form_test.exs
Gday Zach, here's a failing test for when a nested `:single` form contains a nested list. The error seems to indicate that the inner most nested list was not configured (AshPhoenix.Form.NoFormConfigured).
I wouldn't expect the assert to pass, it's just an example that an error was generated, hope it makes sense! I'll have a look at a fix soon if nothing jumps out at you.
=> test: Add failing test

lib/ash_phoenix/form/form.ex, test/form_test.exs, test/support/other_api.ex
=> improvement: Improve error message when incorrect api configured for resource

test/form_test.exs
=> test: Failing test for remove_form reindex

test/form_test.exs
=> test: Failing test for invalid path

lib/ash_phoenix/form/form.ex, test/form_test.exs
=> fix: Add form to single

lib/ash_phoenix/form/form.ex, test/form_test.exs
Fix remove form path when a nested single form contains a list
=> fix: Fix remove form path when a nested single

test/form_test.exs
Pretty sure this is a situation that you fixed yesterday, but the issue is still here for a single resource that holds a list. When you remove the last item from the list and validate, the list is `[%{}]`, instead of `[]`
=> test: Error on submit when removing the last item from a single resource

lib/ash_phoenix/form/form.ex, lib/ash_phoenix/form/no_form_configured.ex
=> docs: Various doc fixes

lib/ash_phoenix/form/form.ex
Signed-off-by: kernel-io <kernel-io@users.noreply.github.com>
=> improvement: handle nil paths in do_decode_path/4

lib/ash_phoenix/form/form.ex
=> improvement: fix & clarify logic in do_decode_path/4 

lib/ash_phoenix/form/form.ex, test/form_test.exs, test/support/registry.ex, test/support/resources/author.ex, test/support/resources/post.ex
Signed-off-by: kernel-io <kernel-io@users.noreply.github.com>
=> fix: respect touched forms in params generation

test/form_test.exs
Signed-off-by: kernel-io <kernel-io@users.noreply.github.com>
=> test: add failing test for remove_form

test/form_test.exs, test/support/resources/post.ex
Signed-off-by: kernel-io <kernel-io@users.noreply.github.com>
=> test: added failing test

test/form_test.exs
=> Failing test for validate_opts issue

lib/ash_phoenix/form/form.ex, test/form_test.exs
Test and fix for broken validate_opts when the added form is a :single type.
refs #41
=> fix: Fix validate_opts when single form

.gitignore, lib/ash_phoenix/types/decimal.ex
=> improvement: decimal protocols

lib/ash_phoenix/filter_form/filter_form.ex, test/filter_form_test.exs
=> feat: append predicate path w/ field when relationship

lib/ash_phoenix/filter_form/filter_form.ex, test/filter_form_test.exs
=> fix: nested groups have correct form names

lib/ash_phoenix/filter_form/filter_form.ex, test/filter_form_test.exs
=> fix: select first public attribute as field when remapping path

lib/ash_phoenix/form/form.ex, test/form_test.exs, test/support/resources/post.ex
=> fix: properly clear value in Form.clear_value/2

lib/ash_phoenix/form/form.ex, test/form_test.exs
=> improvement: accept multiple fields in `AshPhoenix.Form.clear_value/2`

documentation/tutorials/getting-started-with-ash-and-phoenix.md
See original PR for context: https://github.com/ash-project/ash/pull/504
=> docs: ash phoenix getting started guide

lib/ash_phoenix/filter_form/filter_form.ex
=> fix: Patch for new Form Access Protocol

documentation/tutorials/getting-started-with-ash-and-phoenix.md
See companion PR on companion repo
https://github.com/team-alembic/my_ash_phoenix_project/pull/1
=> docs: change getting started directory structure to match realworld

lib/ash_phoenix/form/form.ex
=> fix: use initial form options on failed submit

lib/ash_phoenix/filter_form/filter_form.ex
Hopefully it's not too much? I've trimmed out heaps from my example app.
=> Filter form docs

lib/ash_phoenix/form/form.ex
I've simplified the example too (one layer of nesting)
=> Update form docs to use heex and latest phoenix components

lib/ash_phoenix/filter_form/filter_form.ex
=> fix: Remove the id field from params_for_query reply

lib/ash_phoenix/filter_form/filter_form.ex, test/filter_form_test.exs
=> improvement: Add option to not reset on validate

documentation/tutorials/getting-started-with-ash-and-phoenix.md
I just went through this tutorial and found these two problems.
=> Fix tutorial docs

lib/ash_phoenix/form/form.ex
Improvements to the Form documentation based on my understanding and looking at source code. These very small tweaks would've helped me today.
=> Improve form documentation

documentation/tutorials/getting-started-with-ash-and-phoenix.md
Minor fix, no test updates required.
=> Doc: several small improvements

priv/templates/ash_phoenix.gen.live/show.ex.eex
Its basically a bug fix, but had no tests from before, so in effect there are no regression tests afaik.
Tested it works by using relative path in mix file to ash_phoenix, and running ash_phoenix live generator
=> fix gen.live not adding fields in show

documentation/tutorials/getting-started-with-ash-and-phoenix.md
=> Fix typos in document

documentation/tutorials/getting-started-with-ash-and-phoenix.md
Updated form handler syntax to reflect Phoenix 1.7 changes to form handlers.
Credit: Rebecca Le for suggesting to update form access syntax to use map key access
=> Update liveview form handler syntax

documentation/tutorials/getting-started-with-ash-and-phoenix.md
=> Remove registry from file structure

mix.exs
=> fix: ash version dependency requirement

lib/ash_phoenix/form/form.ex
=> chore: fix params/1 typespec

documentation/tutorials/getting-started-with-ash-and-phoenix.md
Update instructions to be compatible with Ash 3.0.
=> Update instructions to be compatible with Ash 3.0.

lib/ash_phoenix/form/form.ex
=> Fix typo in doc for AshPhoenix.Form.add_form/3

documentation/tutorials/getting-started-with-ash-and-phoenix.md
This pull request has 2 small commits to address issues with the docs:
- The first commit is more functional, and fixes some small issues in the tutorial.
- The second is purely stylistic, and should make the LiveView example look a little nicer when viewed in the browser.
=> docs: fix issues with Getting Started section, and prettify markup

documentation/tutorials/getting-started-with-ash-and-phoenix.md
- Add picosat_elixir dep instructions to the getting started guide
=> Add picosat_elixir dep to the getting started guide

documentation/tutorials/getting-started-with-ash-and-phoenix.md
- [] Bug fixes include regression tests
- [] Features include unit/acceptance tests
.md file change only above not required
updated verbiage and link on "documentation/tutorials/getting-started-with-ash-and-phoenix.md"
[Philosophy Guide] (https://hexdocs.pm/ash/philosophy.html) -> [Design Principles] (https://hexdocs.pm/ash/design-principles.html)
=> fix guide link to philosophy

test/auto_form_test.exs, test/support/domain.ex, test/support/resources/deep_nested_union_resource.ex
=> test_case for nested union types

test/auto_form_test.exs, test/support/domain.ex, test/support/resources/simple_post.ex
=> unions test case for primitive subtype

test/auto_form_test.exs, test/support/resources/simple_post.ex
=> union test cases

test/auto_form_test.exs, test/support/resources/simple_post.ex
=> form value fill for union

lib/ash_phoenix/form/form.ex
=> Cleanup specs with path type

lib/ash_phoenix/form/form.ex
=> Fix typo for documentation.

test/auto_form_test.exs, test/support/resources/foo.ex
Related to this (and other things), passes in 2.1.4
https://github.com/ash-project/ash_phoenix/issues/253
=> test for failing union values

documentation/tutorials/getting-started-with-ash-and-phoenix.md
=> Fix AshJson Link in getting-started-with-ash-and-phoenix.md

lib/ash_phoenix/form/form.ex
Let me know if this is alright, also open to expand.
=> document use of compound types with AshPhoenix.Form

lib/ash_phoenix/gen/live.ex
=> fix: use Igniter.Project.Module.parse to get module names for generator

lib/ash_phoenix/form/form.ex
This PR is a follow-up to #276.
=> Update doc of AshPhoenix.Form.add_error/3 about visibility

lib/ash_phoenix/form/form.ex
=> make arguments have higher precedence in do_value

lib/mix/tasks/ash_phoenix.gen.live.ex
I ran into an issue that I misunderstood what was needed for the mix task, so we executed this task wrong.
I hope this will make it more clear for future users.
=> make gen.live docs more clear with the inputs required

.tool-versions, lib/ash_phoenix/live_view.ex, lib/ash_phoenix/live_view/assign_page_and_stream_result_options.ex, test/live_view_test.exs
Not super happy about the name of the function, but the functionality is good.
=> add in some more liveview docs and add in assignment function

lib/ash_phoenix/form/form.ex
=> fix: Handle invalid params and warn when invalid

lib/ash_phoenix/form/form.ex
#301 continuation
https://github.com/ash-project/ash_phoenix/pull/301#issuecomment-2616456872
=> fix: Handle invalid params and warn when invalid for all for calls

lib/ash_phoenix/form/form.ex
=> fix: Prevent empty errors pass to error class

lib/ash_phoenix/live_view.ex, lib/ash_phoenix/live_view/assign_page_and_stream_result_options.ex, test/live_view_test.exs
Note: I removed the tests cause testing the stream is a bit more tricky than assigning.
=> fix assign page and stream to actually stream the stream

lib/ash_phoenix/form_data/error.ex
=> add error impl for `Ash.Error.Action.InvalidArgument`

lib/ash_phoenix/form/form.ex
=> Update description of the sort_forms function

lib/ash_phoenix/form/form.ex, test/form_test.exs
=> Shows :params in the '## Options' list on document; and add another test for generic action

lib/ash_phoenix/form/form.ex
- Fix broken formatting.
- Correct example function.
=> docs: fix transform_errors option documentation

documentation/topics/forms-for-relationships-between-existing-records.md, mix.exs
Add a guide to document what we learned in this Elixir Forum thread [Creating forms with change manage_relationship not loading values](https://elixirforum.com/t/creating-forms-with-change-manage-relationship-not-loading-values/71498/1)
There is a [Demo App](https://github.com/matt-savvy/ash_phoenix_demo_app) that I created to make sure all the code is correct and working.
=> Add Forms For Relationships Between Existing Records guide

documentation/dsls/DSL-AshPhoenix.md
=> adds missing function generated by example

priv/templates/ash_phoenix.gen.html/resource_form.html.heex.eex
=> Fix: Remove Product from Save Product button - Save button

lib/ash_phoenix/inertia/error.ex
=> fix: ensure nested form errors are included

documentation/tutorials/getting-started-with-ash-and-phoenix.md
Noticed a dead link as I was reading through the docs. This is just my best guess on where it should link now.
=> Update link for resource relationship management

lib/ash_phoenix/form/auto.ex, lib/ash_phoenix/form/wrapped_value.ex, test/auto_form_test.exs, test/support/resources/union_value.ex
This PR addresses #408. Specifically this comment explains what I found:
https://github.com/ash-project/ash_phoenix/issues/408#issuecomment-3234853547
=> Fix error in auto form creation for structs inside of union attributes

lib/ash_phoenix/inertia/error.ex, test/ash_phoenix_inertia_error_test.exs
=> Fixes #416: AshPhoenix.Inertia.Error argument error when reporting validation errors

documentation/dsls/DSL-AshPhoenix.md, lib/ash_phoenix.ex
=> docs: update form_to_* code_interface example
