ash-project/ash_phoenix

- lib/ash_phoenix.ex
It's a bit hard to know how the changes will appear in hexdocs, but there are a couple of issues at the moment:
* code block not working correctly for transform_errors example
* the first option for some of the options lists are getting converted to code blocks because they're spaced in
* and a default value is displayed twice as it's in the description and inferred from the options list
> docs: Minor doc formatting fixes

- lib/ash_phoenix/form/form.ex
- test/form_test.exs
When using `inputs_for`, most (all?) examples with liveview show using it with a for comprehension, even if it's used over a single embedded item. Surface `<Inputs ...>` component also assumes inputs_for is going to return a list.
Here's a test and a naive solution to the issue. There seems to be another issue when nesting other forms under a `:single` resource (the form key for the further nested form is not found). I'm not sure if that's caused by the fix in this PR!
> fix: Wrap single items on to_form

- lib/ash_phoenix/form/form.ex
- test/form_test.exs
Form id is preset to "form" before checking value of `opts[:as]`
> fix: Fix default form id when :as provided

- lib/ash_phoenix/form/form.ex
- test/form_test.exs
Field names are wrong on nested forms on for_update
```
rendered as: directoryemails][0][[email]
should be:   directory[emails][0][email]
```
It might only effect when a `:list` is nested under a `:single`?
> fix: Fix nested form naming

- test/form_test.exs
refs #29 
I've updated the test with my scenario that fails using the rc. It appears the strategy I was using to hide errors on validation until the form was submitted at least once is no longer working:
```elixir
form = AshPhoenix.Form.validate(form, %{"text" => ""}, errors: form.submitted_once?)
```
Not sure if this is a valid way of doing this? I'll reach out on discord!
> Validation issue in rc

- lib/ash_phoenix/form/form.ex
A very simple change that fixes a bug with change detection logic for boolean attribute with a default of `true`. I didn't add a test for this, but did check it locally and it fixes the problem. I can add tests if required.
> fix: Fix logic for change detection of boolean defaults

- lib/ash_phoenix/plug/exception.ex
- test/plug_test.exs
Heavily inspired by https://github.com/phoenixframework/phoenix_ecto/blob/master/lib/phoenix_ecto/plug.ex, that provides appropriate HTTP status codes for Ecto-related errors.
This is only a small subset of the available errors within Ash that could have custom HTTP statuses, but they'd be the most common cases I think.
(shows a 400 error being returned for an invalid primary key, in this case it should be a UUID and is not)
> feat: add custom HTTP status codes for specific types of errors that can be thrown

- documentation/tutorials/getting-started-with-ash-and-phoenix.md
```elixir
defp post_selector(posts) do
for post <- posts do
{:"#{post.title}", post.id}
end
end
```
into:
```elixir
defp post_selector(posts) do
for post <- posts do
{post.title, post.id}
end
end
```
> docs: use string instead of atom for post_selector/1

- lib/ash_phoenix/live_view.ex
I'm updating a legacy app to use the latest Ash releases, but need to keep the old versions of phoenix, liveview, surface etc (I'm not ready to go down that rabbit hole just yet!).
ash_phoenix deps indicates that it supports live view 0.15, but I was getting a compile time error:
```
== Compilation error in file lib/ash_phoenix/live_view.ex ==
** (CaseClauseError) no case clause matching: {:error, :nofile}
lib/ash_phoenix/live_view.ex:592: (module)
```
This PR fixes the issue and I can now compile modern Ash with legacy LiveView
> fix: Support LV 0.15

- documentation/tutorials/getting-started-with-ash-and-phoenix.md
If we have a single post and update that post and do not set post_selector in update_post handle_event we will have the old post still selected.
> docs: Added setting post_selector in update_post

- lib/ash_phoenix/form/form.ex
- lib/ash_phoenix/live_view.ex
- test/form_test.exs
- test/support/resources/post_with_default.ex
Forms submitted outside of LiveView submit empty strings as params for empty fields. Empty fields are problematic for default values because "" is a value, and the resource won't set the default.
To allow the dead view forms, I have added a new
form option. `empty_fields_unset` takes a list of field names. The form will remove empty fields in the `empty_fields_unset` from the params map before the params are processed.
closes #52
> Fixes default values on dead forms

- lib/ash_phoenix/filter_form/filter_form.ex
Implementation of Ash.DataLayer.functions expects a resource, and internally calls Ash.DataLayer.data_layer()
> fix: Remove line causing errors

- documentation/tutorials/getting-started-with-ash-and-phoenix.md
I am salvaging an interesting note found in the AshAuthenticationPhoenix getting started guide, which I am currently rewriting.
I think its place is in this guide.
> docs: add note about dropping database to getting started guide

- lib/ash_phoenix/plug/subdomain_plug.ex
I was going through implementing multi-tenancy in a Phoenix app and noticed the usage documentation had a typo in it. This PR should fix that. Thanks!
> Fix usage documentation

- lib/ash_phoenix/form/form.ex
Fixes the documentation as specified in issue https://github.com/ash-project/ash_phoenix/issues/61
> doc: Add the missing `action` argument to function call

- lib/ash_phoenix/filter_form/filter_form.ex
Fixes a deprecation warning appearing when using latest phoenix:
```
warning: form_for/3 without an anonymous function is deprecated. If you are using Phoenix.LiveView, use the new Phoenix.Component.form/1 component
(phoenix_html 3.3.1) lib/phoenix_html/form.ex:341: Phoenix.HTML.Form.form_for/3
(elixir 1.14.3) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
(phoenix_live_view 0.18.18) lib/phoenix_component.ex:2266: Phoenix.Component."inputs_for (overridable 1)"/1
(phoenix_live_view 0.18.18) lib/phoenix_live_view/tag_engine.ex:68: Phoenix.LiveView.TagEngine.component/3
(my_app 0.1.0) lib/my_app_web/live/filter_form_live.ex:65: anonymous fn/2 in MyAppWeb.FilterFormLive.filter_form_component/1
(phoenix_live_view 0.18.18) lib/phoenix_live_view/diff.ex:517: …
```
> Fix: form_for deprecation warning

- lib/ash_phoenix/filter_form/filter_form.ex
- test/filter_form_test.exs
I'm guessing this is the intended behaviour of remove_component? ie to remove either the group or predicate, not to recursively call remove_component?
> Fix remove_component

- lib/ash_phoenix/form_data/helpers.ex
- mix.exs
Use Logger.warning instead of Logger.warn, [which is deprecated as of elixir 1.15](https://github.com/elixir-lang/elixir/blob/v1.15/CHANGELOG.md#logger-2).
Logger.warning [is available since elixir 1.11](https://hexdocs.pm/logger/1.15.0/Logger.html#warning/2). This project has been updated to require at least elixir 1.11. This should be fine, since `ash` and the other ash ecosystem projects all also require elixir 1.11.
> fix: fix Logger deprecations for elixir 1.15

- documentation/tutorials/getting-started-with-ash-and-phoenix.md
The impetus for this PR is the following [discord message](https://discord.com/channels/711271361523351632/712035333432147989/1157623932136996924).
This PR removes the old registry method of registering resources and uses the "resource" method of adding resources. This eliminates a file and a whole step in the tutorial process.
> Remove the registry and use the resource format

- lib/ash_phoenix/form/form.ex
Tiny documentation change to make it work in modern versions of LiveView.
> Documentation. Add `|> to_form()` to the end of the pipeline for Liveview >= 1.18.2

- .github/ISSUE_TEMPLATE/bug_report.md
- lib/ash_phoenix/gen/live.ex
I believe we need to use an Atom value.
When I tried to use a String I got the following error:
```
(Spark.Error.DslError) [Red.Api.Attempt]
resource:
** (NimbleOptions.ValidationError) invalid value for :plural_name option: expected atom, got: "attempts"
```
> Suggest Atom plural value 👯‍♂️

- lib/ash_phoenix/form/form.ex
The `Enum.uniq()` on error messages does address my initial bug, but I believe this fixes it at the source. When `Ash.phoenix_form.synthesize_action_errors/3` is called recursively, the embedded form errors are added twice. This fixes the issue for me without the need for `Enum.uniq()` in the helper. My robust test suite passes and I did some manual testing in my app, but I don't know if this "fix" is appropriate for everyone.
> fix: errors messages on embedded forms multiply 

- lib/ash_phoenix/gen/live.ex
This removes the 'multiple' attribute from the select input in case the field is an atom field with the `one_of` option set.
Solves: #114
> Remove multiple attribute from select for one_of fields

- lib/ash_phoenix/filter_form/filter_form.ex
The example given for FilterForm worked with LiveView 0.18 but was broken for 0.19. I'm a bit out of the loop with LiveView, but the change here seems to work.
See https://elixirforum.com/t/ashphoenix-filterform-cannot-remove-components/59630
> Update filter form documentation for LiveView 0.19

- .gitpod.yml
- test/form_test.exs
- test/support/resources/author.ex
- test/support/resources/embedded_argument.ex
- test/support/validations/validate_embedded_argument.ex
This may be an X/Y problem, but what I'm trying to do is have an action with an argument that is an embedded resource. The argument resource itself may be valid, but in the context of the parent it is invalid, so the parent creates an add an error with the path to the arguments attribute. That error is not being propagated to the nested form of the argument.
This is a test to reproduce the problem.
Discussed here:
https://elixirforum.com/t/setting-path-on-an-error/59857/3
> Nested form errors for argument attribute

- test/form_test.exs
- test/support/resources/embedded_argument.ex
- test/support/resources/nested_embed.ex
As discussed in Discord, error message on nested form changeset multiply when turned into a Phoenix Form
> Nested form errors should not multiply

- lib/ash_phoenix/form/form.ex
- test/form_test.exs
`AshPhoenix.Form.has_form?` fails when given a string path. 
This happens because the `do_decode_path` functions `raise "Invalid Path: #{original_path}"` instead of `raise InvalidPath, path: original_path`.  The calling functions, however, expect to rescue an `InvalidPath` exception.
This PR:
- switches from raising strings to raising `InvalidPath` exceptions
- adds regression tests
> Fix `do_decode_path` for string paths

- lib/ash_phoenix/form/form.ex
Tested with my demo app - now the page renders if the policy passes, but raises a forbidden error if it does not.
> fix: the API is defined on the form, not on the form.source

- lib/ash_phoenix/live_view.ex
refetch_window is currently being fetched from config directly instead of opts inside config, which causes handle_live to always ignore refetch_window and just rerun the query regardless. 
This PR fixes that.
> fix: properly fetch refetch_window from config

- documentation/tutorials/getting-started-with-ash-and-phoenix.md
No need for `public?: true` for the attributes in the getting started guide.
> docs: no need for `public?: true` for the attributes

- documentation/tutorials/getting-started-with-ash-and-phoenix.md
Since the current version of the Phoenix project generator sets the phoenix_live_view dependency to 0.20.x, update to use the latest comprehension syntax, and remove the mention of having to change some code for versions of LiveView below 0.18.x.
> Update LiveView example in Getting Started guide

- test/form_test.exs
I just added a failing test.
Would you fix this? @zachdaniel 
+ If possible, please fix the ash phoenix version 1.3.4 too, not only 2.0 rc.
> When adding deeply nested form with params, generated form name is not correct

- test/form_test.exs
When removing form in the middle, nested form's name does not be updated correctly.
And form count does not reduce from 3 to 2 in the test.
I just wrote a test for failing case.
Please fix this for 1.3 too, if possible. @zachdaniel
> test: update nested form name correctly when remove form in the middle

- lib/ash_phoenix/form/form.ex
> fix: Pass the tenant to `Ash.can/3` and `Ash.can?/3`

- lib/ash_phoenix/live_view.ex
It's a chore PR that removes `domain` opt from `AshPhoenix.LiveView`.
> Remove domain opt from AshPhoenix.LiveView

- documentation/tutorials/getting-started-with-ash-and-phoenix.md
The rest of the guide refers to `create_post` in the singular, so that is what the code interface function should be named
> docs: Fix typo in Getting Started guide

- lib/ash_phoenix/gen/live.ex
When generating live templates with `mix ash_phoenix.gen.live`, the user is prompted to enter an action name for create and update. When a string is entered, an error occurs because lookups are done via atom, not string.
```
Primary create action not found. Would you like to use one of the following?:
- create [Yn]
Please enter the name of the action you would like to use.
Press enter to cancel and proceed with no create action.
> create
** (RuntimeError) No such create action "create"
(ash_phoenix 2.0.0) lib/ash_phoenix/gen/live.ex:198: AshPhoenix.Gen.Live.action/3
(ash_phoenix 2.0.0) lib/ash_phoenix/gen/live.ex:162: AshPhoenix.Gen.Live.add_resource_assigns/3
```
> fix: Convert entered action names into atoms for lookup in the resource

- lib/ash_phoenix/form/form.ex
- test/form_test.exs
> fix: make sure that _index is correctly updated before and after removal for sparse forms (#196)

- documentation/tutorials/getting-started-with-ash-and-phoenix.md
It is to follow what [AshPhoenix.Form](https://hexdocs.pm/ash_phoenix/AshPhoenix.Form.html) is showing in its documentation. Also it is closer to a real scenario where there are some form validations.
> Use AshPhoenix.Form.submit/2 instead of calling context functions

- lib/mix/tasks/ash_phoenix.gen.html.ex
This PR fixes an issue where trying to execute the command `mix ash_phoenix.gen.html` with Ash Framework 3.0.
Since Ash Framework 3.0, `:private?` has been replaced with `:public?`.
Here the error I got while running the command:
```
** (KeyError) key :private? not found in: %Ash.Resource.Attribute{
name: :isbn,
type: Ash.Type.String,
allow_nil?: false,
generated?: false,
primary_key?: false,
public?: true,
writable?: true,
always_select?: false,
default: nil,
update_default: nil,
description: nil,
source: :isbn,
match_other_defaults?: false,
sensitive?: false,
filterable?: true,
sortable?: true,
constraints: [allow_empty?: false, trim?: true]
}
(ash_phoenix 2.0.4) lib/mix/tasks/ash_phoenix.gen.html.ex:160: Mix.Tasks.AshPhoenix.Gen.Html.attribute_map/1
(elixir 1.16.3) lib/enum.ex:1700: …
```
> Use :public? instead of :private?

- README.md
I noticed that `AshPhoenix.SubdomainPlug` was mentioned twice. Would it make sense to remove the less descriptive one?
> docs: remove duplicate mention of AshPhoenix.SubdomainPlug

- documentation/topics/union-forms.md
> fix: add missing closing `]` in guide

- test/auto_form_test.exs
- test/support/resources/foo.ex
> extend test for deeply nested union stuff

- .formatter.exs
- lib/ash_phoenix/gen/live.ex
- lib/mix/tasks/ash_phoenix.gen.live.ex
- mix.exs
- test/mix/tasks/ash_phoenix.gen.live_test.exs
Atempt 1 to create PR. Once direction is right. I need to figure out how create tests. Perhaps embed a test project to generate the live views from it.
> Migrate phoenix gen to igniter

- documentation/tutorials/getting-started-with-ash-and-phoenix.md
The Get Started with Ash and Phoenix uses `phx.new` to create the project. By using Igniter to create the project, the tutorial can be shortened because Igniter does most of the work in the Add Dependencies section and all the work in the Use AshPostgres.Repo section.
This pull request uses Igniter to create the project and eliminates the steps that are no longer needed when using Igniter.
> Update the tutorial to use Igniter

- lib/ash_phoenix/filter_form/filter_form.ex
```elixir
warning: using map.field notation (without parentheses) to invoke function AshPostgres.Functions.Like.args() is deprecated, you must add parentheses instead: remote.function()
(ash_phoenix 2.1.12) lib/ash_phoenix/filter_form/filter_form.ex:917: anonymous fn/1 in AshPhoenix.FilterForm.predicates/1
```
> fix warning in filter_form.ex

- lib/ash_phoenix/form/form.ex
- test/form_test.exs
I *think* the logic is correct, to fix another issue I spotted with adding/removing forms using the new drop param method. When the last element is deleted, `[0]` stays in the drop params meaning that even after adding a new one, it will get deleted again.
Without the code change, the test fails with the count being 0, not 1.
> fix: Allow re-adding forms to a nested form after deleting the last one from a list

- lib/ash_phoenix/filter_form/filter_form.ex
There were a few places where `AshPhoenix.fun()` was supposed to be `AshPhoenix.FilterForm.fun()`
> chore(docs): Correct typos for FilterForm docs

- lib/ash_phoenix/form/no_form_configured.ex
Investigating why I was getting an error message telling me there was no relationship for my form, when there clearly is - this fixes it!
> fix: Show correct error message when no form is configured but a relationship is present

- lib/ash_phoenix/form/form.ex
- test/form_test.exs
#229 
Hope this is the right approach.
I expanded one test covering this fix, not sure if that counts for the check.
Question about `ash_errors`, should the path for it also be parsed? 
Also, I don't see a difference between `errors` and `ash_errors` other then `errors` does transform and format.
Should I add `@doc` and `@spec` for `ash_errors`?
> fix: In AshPhoenix.Form.errors parse path before errors get

- lib/ash_phoenix/live_view.ex
Fixes #322
Encountered a bug where using `pagination keyset?: true` can click the "previous" button on the very first page. Since the initial state for `before`/`after` are both `nil` and `more?: true`, we added a function clause for `page_link_params/2`.
> Additional function clause for keyset pagination (page_link_params)

- documentation/topics/union-forms.md
The examples in the union forms documentation were failing to update values because the embedded resource attributes weren't properly marked as public (`public? true`). This fix ensures the documented examples work correctly when copying and pasting.  Without this change, users would encounter silent failures when following the examples as the form attributes would be inaccessible for updates.
In order to reproduce the problem I've created a repo https://github.com/minibikini/ash_phoenix_union_form_example which now has a working example of a union form in Ash, perhaps someone will find it useful.
> docs: fix union forms examples by adding missing public attributes

- lib/ash_phoenix/form_data/helpers.ex
Since upgrading to ash_phoenix v2.1.21 I started seeing warnings like this on form validation:
[warning] Unhandled error in form submission for Rts.Bookings.Location.create
This error was unhandled because Ash.Error.Unknown.UnknownError does not implement the `AshPhoenix.FormData.Error` protocol.
** (Ash.Error.Unknown.UnknownError) nil
At first I thought I had just broken my code in some way. 
But I since traced it to this commit: [64c578c](https://github.com/ash-project/ash_phoenix/commit/64c578cd017103f518a51933bc89680b5515b290)
Calling Ash.Error.to_error_class([]) with empty list (i.e. no errors) returns an unknown error.
Not sure if this is how it should be fixed, but it does stop the warning from being issued. Cheers.
> fix: unhandled error in form submission warning

- test/auto_form_test.exs
- test/form_test.exs
Also refactored a bit to my liking, do shout if you think it's no good.
> We can just submit the forms with form.raw_params to silence the warning and use the last params
But I didn't do that yea 😓  I just prepared params and used it multiple times.
wdyt?
> fix: Form submit missing params option warning in tests

- documentation/topics/nested-forms.md
a typo "_form" is
```
value={location_form.index}
```
fixed with
```
value={location.index}
```
> fix typo for nested_form documentation

- lib/ash_phoenix/helpers.ex
- lib/ash_phoenix/live_view/subdomain_hook.ex
- lib/ash_phoenix/plug/subdomain_plug.ex
- test/helpers_test.exs
- Add `AshPhoenix.LiveView.SubdomainHook` to make it easier to assign the `current_tenant` from the subdomain like `AshPhoenix.SubdomainPlug`
- Create `AshPhoenix.Helpers.get_subdomain/2` to consolidate the logic for both `SubdomainPlug` and `SubdomainHook`
- Add tests for `AshPhoenix.Helpers.get_subdomain/2`
To use the hook, you can do one of the following:
```elixir
live_session :foo, on_mount: [
AshPhoenix.LiveView.SubdomainHook,
]
```
This will assign the tenant's subdomain value to `:current_tenant` key by default.
If you want to specify the assign key
```elixir
live_session :foo, on_mount: [
{AshPhoenix.LiveView.SubdomainHook, [assign: :different_assign_key}]
]
```
You can also provide `handle_subdomain` module, function, arguments tuple that will be run after the tenant is …
> improvement: Add subdomain live_view hook

- .formatter.exs
- lib/mix/tasks/ash_phoenix.install.ex
Putting this in a PR because this is the first time I've ever created an Igniter installer - do I need more in the `info` callback? I copied and pasted this from the Ash Igniter installer and ripped out all the bits I didn't need.
I tested this by pointing Tunez to my local AshPhoenix checkout - I could then run `mix ash_phoenix.install`, which added `ash_phoenix` to the formatter list. Running `mix format` then removes parens from code like `form(:create_artist, args: [:artist_id])`.
> feat: Add Igniter installer and set up DSL formatting

- lib/ash_phoenix/helpers.ex
- test/helpers_test.exs
Allows the use of `Phoenix.LiveView.Socket` in the `get_subdomain` function in alignment with the [`SubdomainPlug` docs](https://hexdocs.pm/ash_phoenix/AshPhoenix.SubdomainPlug.html).
One other problem I ran into while following the docs was that the assign `current_tenant` was set as `nil` before `handle_params` in my LiveView was reached. The example code (again, from the `SubdomainPlug` docs) reads as follows:
```ex
def handle_params(params, uri, socket) do
socket =
assign_new(socket, :current_tenant, fn ->
AshPhoenix.SubdomainPlug.live_tenant(socket, uri)
end)
...
end
```
But of course, because the `current_tenant` is already set, `live_tenant` is never called. I couldn't find anywhere in the `ash_phoenix` repo where this might have been predefined, but I did see it being set in …
> Fix: Accept Phoenix.LiveView.Socket in SubdomainPlug

- lib/ash_phoenix/form/form.ex
- test/form_test.exs
AshPhoenix.Form.update_params() may fail on a AshPhoenix.Form.for_action() because of the :raw_params field was not initialized.
Error:
** (BadMapError) expected a map, got: nil
> Initialize :raw_params field of for_action() Form

- lib/ash_phoenix/form/form.ex
- test/form_test.exs
- usage-rules.md
> Improvement: Add `to_form/2` in usage rules and improve error message when accessing a form without `to_form/2`

- lib/ash_phoenix/live_view.ex
This should prevent the generation of:
- `prev` link when we’re on the first page
- `next` link when we’re on the first page that contains all available results
First encountered by [Jaeyson Anthony on Discord](https://discord.com/channels/711271361523351632/1298629277524295700/1348927149049905163) and just now by me in my personal project.
> Fix edge cases with keyset navigation

- lib/ash_phoenix/form/form.ex
- test/auto_form_test.exs
- test/support/resources/union_value.ex
Fixes #414. 
The issue was that the `_union_type` was not set if the `value` inside of the `Union` was not  a resource. 
I would think that is a bug, but maybe I'm missing something so it's probably good that someone validates this.
> Fix error in `Form.for_update` on resource with `:date` type in `:union` types constraint

- lib/ash_phoenix/live_view.ex
Introduce `params_to_page_opts/3` for explicit count queries, soft deprecate `page_from_params/3`
This change is covered by doctests and no additional unit tests are added
Closes #420
> Feat: only allow explicit count queries in pagination

- test/ash_phoenix_test.exs
- test/support/domain.ex
- test/support/resources/comment.ex
Custom inputs transformations are not taken into account when using AshPhoenix's
`forms`. Therefore, this test fails with a "post_id is required" message, even
though we have passed the a post as the first argument to
`form_to_create_with_custom_input`.
> test: Add failing test for custom inputs in forms
